---
version: '3.3'
services:
  postgresql:
    image: mdillon/postgis:9.6-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  pact-broker:
    image: pactfoundation/pact-broker:latest
    ports:
      - '80:9292'
    depends_on:
      - postgresql
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: magic8ball
      PACT_BROKER_DATABASE_HOST: postgresql
      PACT_BROKER_DATABASE_NAME: pact_broker
      PACT_BROKER_LOG_LEVEL: INFO
